name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          id: win

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@master
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main
          target: ${{ matrix.config.id }}
